BUILD_DIR=em-build
COPASIJS_DEPENDENCY_DIR=dev/em-dependencies
BUILD_TYPE=Release
INSTALL_PREFIX=dist-node

emcmake cmake -B $BUILD_DIR \
        -DCMAKE_BUILD_TYPE=$BUILD_TYPE \
        -DCOPASIJS_DEPENDENCY_DIR=$COPASIJS_DEPENDENCY_DIR \
        -DCMAKE_INSTALL_PREFIX=$INSTALL_PREFIX \
        -DCOPASIJS_ENVIRONMENT=node \
        -DCOPASIJS_INCLUDE_EXAMPLE_FILES=ON

cmake --build $BUILD_DIR --config $BUILD_TYPE
cmake --install $BUILD_DIR --config $BUILD_TYPE

